### ISSUE TITLE
Sidebar displays multiple numbers

### ISSUE THREAD

**Issue by jmonman7** [fbgallet/roam-extension-stats#1]
Hi Fabrice, I've attached a picture of what I am seeing when I open my sidebar. 
<img width="463" alt="CleanShot 2023-03-13 at 11 26 22" src="https://user-images.githubusercontent.com/69330400/224795561-4882f6c9-8502-4be4-bd78-3566ac66d93b.png">

**Comment by fbgallet** [comment]
Hi, thanks! This bug is fixed in the last update published 3 days ago but not yet merged by the Roam team.

**Comment by jmonman7** [comment]
Awesome, thank you! Appreciate all you do.
